ditteau_data_v1:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: snowflake_jwt
      private_key_path: "{{ env_var('SNOWFLAKE_KEYPATH')}}"
      role: "{{ env_var('SNOWFLAKE_DEV_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DEV_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_DEV_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_DEV_SCHEMA') }}"  # Default schema (overridden by dbt_project.yml)
      threads: 4
      client_session_keep_alive: True  # Change to True for dev
      query_tag: "dbt_dev_{{ env_var('USER', 'unknown') }}"  # Track queries
   
    test:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: snowflake_jwt
      private_key_path: "{{ env_var('SNOWFLAKE_KEYPATH')}}"
      role: "{{ env_var('SNOWFLAKE_TEST_ROLE', env_var('SNOWFLAKE_DEV_ROLE')) }}"  # Falls back to dev role
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE', env_var('SNOWFLAKE_DEV_WAREHOUSE')) }}"  # Falls back to dev warehouse
      schema: "{{ env_var('SNOWFLAKE_TEST_SCHEMA', env_var('SNOWFLAKE_DEV_SCHEMA')) }}"
      threads: 4
      client_session_keep_alive: True
      query_tag: "dbt_test_{{ env_var('USER', 'unknown') }}"
        
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_PROD_USER') }}" 
      # Key-pair auth for service accounts
      authenticator: snowflake_jwt
      private_key_path: "{{ env_var('SNOWFLAKE_KEYPATH') }}"
      role: "{{ env_var('SNOWFLAKE_PROD_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_PROD_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_PROD_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_PROD_SCHEMA') }}"  # Default schema
      threads: 8
      client_session_keep_alive: True
      query_tag: "dbt_prod_{{ env_var('DBT_CLOUD_JOB_ID', 'manual') }}"
      