ditteau_data_v1:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: syaxlgh-data-platform
      database: DITTEAU_DATA_DEV
      warehouse: TRANSFORM_DEV
      schema: deterge
      role: SYSADMIN
      authenticator: snowflake
      threads: 4
   
    type: snowflake
      account: syaxlgh-data-platform
      database: DITTEAU_DATA_TEST
      warehouse: TRANSFORM_TEST
      schema: deterge
      role: SYSADMIN
      authenticator: snowflake
      threads: 4
        
    prod:
      type: snowflake
      account: syaxlgh-data-platform
      database: DITTEAU_DATA_PROD
      warehouse: TRANSFORM_PROD
      schema: deterge
      role: SYSADMIN
      authenticator: snowflake
      threads: 8
  